### ISSUE TITLE
Premature end of stream when reading from NetworkStream in .Net 6 on Linux

### ISSUE THREAD

**Issue by ghost** [peteroupc/CBOR#65]
Hello,

we have a problem when reading CBOR messages from a network stream in .Net 6 on a linux machine. That is, `CBORObject.Read` throws a CBORException 
```
[2023.04.03 14:28:25:592] [CborReceiver] Exception during CBOR read
PeterO.Cbor.CBORException: Premature end of stream
   at PeterO.Cbor.CBORReader.ReadByteData(Stream stream, Int64 uadditional, Stream outputStream)
   at PeterO.Cbor.CBORReader.ReadStringArrayMap(Int32 type, Int64 uadditional)
   at PeterO.Cbor.CBORReader.ReadInternal()
   at PeterO.Cbor.CBORReader.ReadStringArrayMap(Int32 type, Int64 uadditional)
   at PeterO.Cbor.CBORReader.ReadInternal()
   at PeterO.Cbor.CBORReader.Read()
   at PeterO.Cbor.CBORObject.Read(Stream stream)
   at Mabri.Module.P126.Embedded.Ring.Communication.Cbor.CborReceiver.ReadNextCborObject() in
/home/pi/Documents/P126.Fabian/Mabri.Module.P126.Embedded.Ring/Communication/Cbor/CborReceiver.cs:line 83
[2023.04.03 14:28:25:596] [CborReceiver] An unexpected CBOR exception occured. As a workaround, the client is
disconnected.
```
when it is actually receiving a message. Before, the call simply blocks as expected. At first, we believed this problem to be caused by the network stream timing out while reading the message (because bytes may be send in chunks). However, we disabled all timeouts and the problem persists. We inspected the source code and believe that this check fails:
```      
if (PropertyMap.ExceedsKnownLength(stream, uadditional)) {
      throw new CBORException("Premature end of stream");
}
```
However, we don't understand what is happening as the `NetworkStream` does not inherit from `MemoryStream` and does not support seeking. As for the payload, we send some an ordered map with mostly primitive types but also a jpeg-encoded image. The jpeg data is not encoded as a string but added directly to the ordered map:
```
var cborObject = CBORObject.NewOrderedMap();
cborObject.Add(MessageField.Red1ImageBytes + offset, GetImageBytes(_markingResult.Markings[wavelengthIndex]));
```
We have a unit test which creates the CBOR object, converts to bytes, writes the bytes to a memory stream and parses the cbor object from the stream. This works as expected, both on linux and windows.

We are using library version 4.5.2 as provided by the official NuGet source. Any help or advice would be appreciated. Thanks in advance!

**Comment by MV-Fabian** [comment]
We have found that increasing the JPEG compression is a workaround. Now, the transferred image is 9 instead of 90kbytes and we can parse the message. However, I don't believe this is intended behavior and should still be reviewed.

**Comment by vitidev** [comment]
Maybe this is related to this [issue](https://github.com/peteroupc/CBOR/issues/58), that was fixed, but it looks like the nuget package has not been updated

**Comment by peteroupc** [comment]
Can you see if this problem goes away with the most recent code in the repository?

**Comment by DaveMabri** [comment]
Hello Peter, 
I'm working on the same project as the guy who posed the question. 
We are using the nuget package 4.5.2 of your Repo, which is the version with the most recent code. 
We are still receiving the exact same error while reading from the stream. 

Have you got any suggestions on how to handle with it?
Thank you in advance!

**Comment by peteroupc** [comment]
I have pushed version 4.5.3.

**Comment by peteroupc** [comment]
Should be resolved.

**Comment by knutwannheden** [comment]
I am still seeing this error sometimes when deserializing data from a NetworkStream. I will try to gather more data and hopefully I will be able to create something reproducible.
